// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwbjlklhsasynzwogrsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3Ympsa2xoc2FzeW56d29ncnN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MTg5NzYsImV4cCI6MjA3Mzk5NDk3Nn0.FxAZcHhj1lXiYudNzHrMCX_szSzZ5cVaXMZBNQ6-naY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});